---
- hosts: all
  remote_user: root
  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        cache_valid_time: 1800
        update_cache: yes
      tags:
        - build
  post_tasks:
    - name: "Copy default-gems"
      copy:
        src: "{{ role_path }}/files/default-gems"
        dest: "{{ ansible_env.HOME }}/.rbenv/default-gems"
    - name: "Start unison sync"
      script: /usr/bin/flock -n /tmp/synclock -c 'unison gits' > /dev/null

  roles:
    - role: weareinteractive.unison
      become: yes
      unison_user: vagrant
      unison_configs:
        - name: gits
          src: /home/vagrant/host_home/gits
          dest: /home/vagrant/gits
          ignore:
            - Path */build/*
            - Name *.log
            - Path */node_modules/*
            - Path */vendor/*
            - Path */cache/*
            - Path */tmp/*
    - krypton
    - role: bearandgiraffe.heroku-cli
      become: yes
    - dev
    - role: simplifield.postgres
      become: yes
    - role: geerlingguy.redis
      become: yes
    - role: silverlogic.rabbitmq
      rabbitmq_ssl: false
      become: yes
    - role: geerlingguy.mailhog
      become: yes
    - role: zzet.rbenv
      env: user
      default_ruby: 2.6.3
      rubies:
        - version: 2.6.4
      rbenv_users:
        - vagrant
      rbenv_plugins:
        - { name: "ruby-build",
            repo: "https://github.com/rbenv/ruby-build.git",
            version: "master" }
        - { name: "rbenv-default-gems",
            repo: "https://github.com/rbenv/rbenv-default-gems.git",
            version: "master" }
        - { name: "rbenv-update",
            repo: "https://github.com/rkh/rbenv-update.git",
            version: "master" }
    - role: eendroroy.nodenv
      nodenv:
        plugins:
          - { name: node-build, repo: 'https://github.com/nodenv/node-build.git' }
      nodes:
        - version: 9.11.2
        - version: 9.11.1