---
- hosts: all
  remote_user: root
  # connection: local
  vars_files:
    - ../config.yml
    - vars.yml
  pre_tasks:
    - name: Update apt
      become: yes
      apt:
        cache_valid_time: 1800
        update_cache: yes
      tags:
        - build
  post_tasks:
    ### Postgresql no password
    - name: "No-password postgres"
      become: yes
      copy:
        src: files/pg_hba.conf
        dest: /etc/postgresql/9.6/main/pg_hba.conf
    - name: Reload postgres
      become: yes
      service:
        name: postgresql
        state: reloaded
    - name: Ensure postgres vagrant user
      become: yes
      postgresql_user:
        name: vagrant
        state: present
        role_attr_flags: SUPERUSER
    - name: Ensure rbenv config
      blockinfile:
        dest: "{{ ansible_env.HOME }}/.zshrc"
        block: |
          export PATH="$HOME/.rbenv/bin:$PATH"
          eval "$(rbenv init -)"
          POWERLEVEL9K_RBENV_PROMPT_ALWAYS_SHOW=true
        marker: '# {mark} ANSIBLE MANAGED BLOCK - rbenv'
    - name: Set ZSH font
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        insertbefore: BOF
        line: "POWERLEVEL9K_MODE={{ zsh_pwerlevel_mode }}"
  roles:
    - role: viasite-ansible.zsh
      become: yes
    - role: jdauphant.unbound
      become: yes
      # Forward server to Cloudflare DNS
      unbound_forward_zone:
        - "1.1.1.1@853#cloudflare-dns.com"
        - "1.0.0.1@853#cloudflare-dns.com"
    - dev
    - role: weareinteractive.unison
      become: yes
      unison_user: vagrant
      unison_configs:
        - name: gits
          src: "/home/vagrant/host_home/{{ host_workspace_path }}"
          dest: /home/vagrant/gits
          ignore:
            - Path */build/*
            - Name *.log
            - Path */node_modules/*
            - Path */vendor/*
            - Path */cache/*
            - Path */tmp/*
    - krypton
    - role: bearandgiraffe.heroku-cli
      become: yes
    - role: simplifield.postgres
      become: yes
    - role: geerlingguy.redis
      become: yes
    - role: silverlogic.rabbitmq
      rabbitmq_ssl: false
      become: yes
    - role: geerlingguy.mailhog
      become: yes
    - role: zzet.rbenv
      rbenv:
        env: user
        version: v1.1.2
        default_ruby: 2.6.3
        rubies:
          - version: 2.6.3
      default_gems_file: "{{ playbook_dir }}/files/default-gems"
      rbenv_users:
        - vagrant
      rbenv_plugins:
        - { name: "ruby-build",
            repo: "https://github.com/rbenv/ruby-build.git",
            version: "master" }
        - { name: "rbenv-default-gems",
            repo: "https://github.com/rbenv/rbenv-default-gems.git",
            version: "master" }
        - { name: "rbenv-update",
            repo: "https://github.com/rkh/rbenv-update.git",
            version: "master" }
