  - src: simplifield.postgres
  - src: geerlingguy.redis
  - src: geerlingguy.mailhog
  - src: zzet.rbenv
  - src: weareinteractive.unison
  - src: bearandgiraffe.heroku-cli
  - src: jdauphant.unbound
  - src: viasite-ansible.zsh
