  - src: simplifield.postgres
  - src: geerlingguy.redis
  - src: silverlogic.rabbitmq
  - src: geerlingguy.mailhog
  - src: zzet.rbenv
  - src: weareinteractive.unison
  - src: eendroroy.nodenv
  - src: bearandgiraffe.heroku-cli
