- name: Add heroku key
  become: yes
  apt_key:
    url: http://toolbelt.herokuapp.com/apt/release.key
    state: present

- name: Ensure unison job exists
  cron:
    name: "sync gits with host"
    minute: "*/30"
    job: "{{ ansible_env.HOME }}/bin/workspace_sync > /dev/null"

- name: Ensure time sync job exists
  become: yes
  cron:
    name: "timesync"
    minute: "*/13"
    job: "ntpdate pool.ntp.org > /dev/null"

- name: "Install basic dependencies"
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - ca-certificates
    - software-properties-common
    - dirmngr
    - gcc
    - wget
    - libssl-dev
    - libreadline-dev
    - zlib1g-dev
    - libcurl4
    - libcurl4-openssl-dev
    - libpq-dev
    - unzip
    - python-psycopg2
    - python3-pip
    - python3-setuptools
    - glances

# - name: "Python dependencies"
#   become: yes
#   pip: 
#     executable: pip3
#     name: "glances"
#     name: "{{ packages }}"
#     state: present
#   vars:
#     packages:
#       - setuptools
#       - psycopg2-binary
#       - glances

- name: "Install helpful things"
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - tmux

