---
# tasks file for provision/roles/dev
- name: Ensure ~/gits
  file:
    path: "{{ ansible_env.HOME }}/gits"
    state: directory
    mode: '0755'

### home dir sync
- name: $HOME templating
  import_tasks: home_sync.yml

### Bash themes
- name: Setup bash themes
  import_tasks: ohmybash.yml

### Cleanup
- name: Install dependencies
  import_tasks: dependencies.yml

### NordVPN
- name: Install NordVPN
  import_tasks: nordvpn.yml

### ~/bin
- name: Setup local bin directory
  import_tasks: localbin.yml

### ngrok
- name: Setup ngrok
  import_tasks: ngrok.yml

### nodenv
- name: Setup nodenv
  import_tasks: nodenv.yml
